version: '3'
volumes:
  node_modules:

services:
  extension_xv_datalake_dev:
    container_name: extension_xv_datalake_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d --no-rich-logging
    volumes:
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .extension-xv-datalake_dev.env

  extension_xv_datalake_bash:
    container_name: extension_xv_datalake_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .extension-xv-datalake_dev.env

  extension_xv_datalake_test:
    container_name: extension_xv_datalake_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .extension-xv-datalake_dev.env
